repos:
  - repo: https://github.com/EbodShojaei/bake
    rev: v1.4.5
    hooks:
      - id: mbake-format
        args:
          - --config
          - .bake.toml
      - id: mbake-validate
        args:
          - --config
          - .bake.toml
        exclude: ^backend/

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint
        args:
          - --format
          - parsable
          - --strict
        exclude: (.github|pnpm-lock.yaml)

  - repo: https://github.com/ansible/ansible-lint
    rev: v26.1.1
    hooks:
      - id: ansible-lint
        additional_dependencies:
          - ansible-core
        args:
          - -c
          - .github/ansible/.ansible-lint.yaml
          - .github/ansible
        files: ^\.github/ansible/.*\.ya?ml$
        language_version: python3
        pass_filenames: true

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.2
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format

  - repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django
        files: templates/.*.html
        entry: djlint --reformat
        types:
          - html

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint
        args:
          - --fix
        files: \.md$

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args:
          - --implicit_start
          - --mapping=2
          - --offset=2
          - --sequence=4
        exclude: (.github|pnpm-lock.yaml)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        additional_dependencies:
          - strawberry-graphql-django
          - types-lxml
          - types-python-dateutil
          - types-PyYAML
          - types-requests
        args:
          - --config-file
          - backend/pyproject.toml

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: frontend/src/types/__generated__
        exclude_types:
          - svg
      - id: file-contents-sorter
        args:
          - --unique
        files: (.github/workflows/check-pr-issue-skip-usernames.txt|cspell/custom-dict.txt)
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: name-tests-test
        args:
          - --pytest
        exclude: backend/tests/data
        files: backend/tests
      - id: trailing-whitespace
        exclude: pnpm-lock.yaml

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.16.1
    hooks:
      - id: pyproject-fmt
