version: '3.8'
services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: nestbot_redis
    ports:
      - "6379:6379"
    volumes:
      - ./users.acl:/users.acl
    command: redis-stack-server --aclfile /users.acl
    restart: always
