services:
  backend:
    container_name: nest-backend
    command: >
      sh -c '
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      '
    image: nest-local-backend
    build:
      context: ../../backend
      dockerfile: ../docker/backend/Dockerfile.local
    depends_on:
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
    env_file: ../../backend/.env
    environment:
      DJANGO_DB_HOST: ${DJANGO_DB_HOST:-db}
      DJANGO_DB_NAME: ${DJANGO_DB_NAME:-nest_db_dev}
      DJANGO_DB_PASSWORD: ${DJANGO_DB_PASSWORD:-nest_user_dev_password}
      DJANGO_DB_PORT: ${DJANGO_DB_PORT:-5432}
      DJANGO_DB_USER: ${DJANGO_DB_USER:-nest_user_dev}
      DJANGO_REDIS_HOST: ${DJANGO_REDIS_HOST:-nest-cache}
      DJANGO_REDIS_PASSWORD: ${DJANGO_REDIS_HOST:-nest-cache-password}
    networks:
      - nest-network
    ports:
      - 8000:8000
    volumes:
      - ../../backend:/home/owasp
      - backend-venv-e2e:/home/owasp/.venv

  cache:
    command: >
      sh -c '
        redis-server --requirepass $$REDIS_PASSWORD --maxmemory 25mb --maxmemory-policy allkeys-lru
      '
    container_name: nest-cache
    image: redis:8.0.5-alpine3.21
    environment:
      REDIS_PASSWORD: ${DJANGO_REDIS_PASSWORD:-nest-cache-password}
    healthcheck:
      interval: 5s
      retries: 5
      test: [CMD, redis-cli, -a, $$REDIS_PASSWORD, ping]
      timeout: 5s
    networks:
      - nest-network
    volumes:
      - cache-data-e2e:/data

  db:
    container_name: nest-db
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: ${DJANGO_DB_NAME:-nest_db_dev}
      POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD:-nest_user_dev_password}
      POSTGRES_USER: ${DJANGO_DB_USER:-nest_user_dev}
    healthcheck:
      interval: 5s
      retries: 5
      test: [CMD, pg_isready, -U, '${DJANGO_DB_USER:-nest_user_dev}', -d, '${DJANGO_DB_NAME:-nest_db_dev}']
      timeout: 5s
    networks:
      - nest-network
    volumes:
      - db-data-e2e:/var/lib/postgresql/data

  docs:
    container_name: nest-docs
    command: >
      sh -c '
        mkdocs serve -a 0.0.0.0:8001
      '
    build:
      context: ../../
      dockerfile: docker/docs/Dockerfile.local
    networks:
      - nest-network
    ports:
      - 8001:8001
    volumes:
      - ../../docs:/home/owasp/docs
      - docs-venv-e2e:/home/owasp/.venv

  frontend:
    container_name: nest-frontend
    command: >
      sh -c '
        pnpm run dev
      '
    build:
      context: ../../frontend
      dockerfile: ../docker/frontend/Dockerfile.local
    depends_on:
      - backend
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_ENV=development
    networks:
      - nest-network
    ports:
      - 3000:3000
    volumes:
      - ../../frontend:/home/owasp
      - frontend-next-e2e:/home/owasp/.next
      - frontend-node-modules-e2e:/home/owasp/node_modules

  worker:
    container_name: nest-worker
    command: >
      sh -c '
        python manage.py rqworker ai --with-scheduler
      '
    image: nest-local-backend
    depends_on:
      backend:
        condition: service_started
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
    env_file: ../../backend/.env
    environment:
      DJANGO_DB_HOST: ${DJANGO_DB_HOST:-db}
      DJANGO_DB_NAME: ${DJANGO_DB_NAME:-nest_db_dev}
      DJANGO_DB_PASSWORD: ${DJANGO_DB_PASSWORD:-nest_user_dev_password}
      DJANGO_DB_PORT: ${DJANGO_DB_PORT:-5432}
      DJANGO_DB_USER: ${DJANGO_DB_USER:-nest_user_dev}
      DJANGO_REDIS_HOST: ${DJANGO_REDIS_HOST:-cache}
      DJANGO_REDIS_PASSWORD: ${DJANGO_REDIS_PASSWORD:-nest-cache-password}
    networks:
      - nest-network
    volumes:
      - ../../backend:/home/owasp
      - backend-venv-e2e:/home/owasp/.venv

networks:
  nest-network:

volumes:
  backend-venv-e2e:
  cache-data-e2e:
  db-data-e2e:
  docs-venv-e2e:
  frontend-next-e2e:
  frontend-node-modules-e2e:
