services:
  backend:
    container_name: fuzz-nest-backend
    command: >
      sh -c '
        python manage.py migrate &&
        gunicorn wsgi:application --bind 0.0.0.0:9500
      '
    build:
      context: ../../backend
      dockerfile: docker/Dockerfile
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    env_file: ../../backend/.env.fuzz.example
    networks:
      - fuzz-nest-network
    ports:
      - 9500:9500
    healthcheck:
      interval: 10s
      retries: 10
      test: >
        sh -c '
          wget --spider http://backend:9500/a/
        '
      timeout: 10s
      start_period: 5s

  data-loader:
    container_name: fuzz-nest-data-loader
    image: pgvector/pgvector:pg16
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_healthy
    environment:
      PGPASSWORD: ${DJANGO_DB_PASSWORD:-nest_user_fuzz_password}
      POSTGRES_USER: ${DJANGO_DB_USER:-nest_user_fuzz}
      POSTGRES_DB: ${DJANGO_DB_NAME:-nest_db_fuzz}
    volumes:
      - ../../backend/data:/data:ro
    networks:
      - fuzz-nest-network
    command: >
      sh -c '
        echo "Loading data from dump..." &&
        pg_restore -h db -U $$POSTGRES_USER -d $$POSTGRES_DB /data/nest.dump &&
        echo "Data loading completed."
      '
  db:
    container_name: fuzz-nest-db
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: ${DJANGO_DB_NAME:-nest_db_fuzz}
      POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD:-nest_user_fuzz_password}
      POSTGRES_USER: ${DJANGO_DB_USER:-nest_user_fuzz}
    healthcheck:
      interval: 5s
      retries: 5
      test: [CMD-SHELL, pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost -p 5432]
      timeout: 5s
    networks:
      - fuzz-nest-network
    volumes:
      - fuzz-db-data:/var/lib/postgresql/data
    ports:
      - 5434:5432

  cache:
    command: >
      sh -c '
        redis-server --requirepass $$REDIS_PASSWORD --maxmemory 100mb --maxmemory-policy allkeys-lru
      '
    container_name: fuzz-nest-cache
    image: redis:8.0.5-alpine3.21
    environment:
      REDIS_PASSWORD: ${DJANGO_REDIS_PASSWORD:-nest-fuzz-cache-password}
    healthcheck:
      interval: 5s
      retries: 5
      test: [CMD, redis-cli, -a, $$REDIS_PASSWORD, ping]
      timeout: 5s
    networks:
      - fuzz-nest-network
    volumes:
      - fuzz-cache-data:/data

  graphql:
    container_name: fuzz-nest-graphql
    build:
      context: ../../backend/docker/fuzz
      dockerfile: Dockerfile
    environment:
      BASE_URL: http://backend:9500
      TEST_FILE: test_graphql.py
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - fuzz-nest-network

  rest:
    container_name: fuzz-nest-rest
    build:
      context: ../../backend/docker/fuzz
      dockerfile: Dockerfile
    environment:
      BASE_URL: http://backend:9500
      REST_URL: http://backend:9500/api/v0
      TEST_FILE: test_rest.py
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - fuzz-nest-network

networks:
  fuzz-nest-network:

volumes:
  fuzz-db-data:
  fuzz-cache-data:
