services:
  backend:
    container_name: e2e-nest-backend
    command: >
      sh -c '
        gunicorn wsgi:application --bind 0.0.0.0:9000
      '
    build:
      context: ../backend
      dockerfile: docker/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file: ../backend/.env.e2e.example
    networks:
      - e2e-nest-network
    ports:
      - 9000:9000
    healthcheck:
      interval: 10s
      retries: 10
      test: >
        sh -c '
          wget --spider http://backend:9000/a/
        '
      timeout: 10s
      start_period: 5s
  db:
    container_name: e2e-nest-db
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: ${DJANGO_DB_NAME:-nest_db_e2e}
      POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD:-nest_user_e2e_password}
      POSTGRES_USER: ${DJANGO_DB_USER:-nest_user_e2e}
    healthcheck:
      interval: 5s
      retries: 5
      test: [CMD-SHELL, pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost -p 5432]
      timeout: 5s
    networks:
      - e2e-nest-network
    volumes:
      - e2e-db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  frontend:
    container_name: e2e-nest-frontend
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile.e2e.test
    command: >
      sh -c '
        pnpm run test:e2e
      '
    depends_on:
      backend:
        condition: service_healthy
    env_file: ../frontend/.env.e2e.example
    networks:
      - e2e-nest-network

  graphql:
    container_name: e2e-nest-fuzz-graphql
    build:
      context: ../backend/docker
      dockerfile: Dockerfile.fuzz
    entrypoint:
      - /app/entrypoint.sh
    environment:
      GRAPHQL_URL: http://backend:9000/graphql/
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - e2e-nest-network

networks:
  e2e-nest-network:

volumes:
  e2e-db-data:
