services:
  backend:
    container_name: fuzz-nest-backend
    command: >
      sh -c '
        python manage.py migrate &&
        gunicorn wsgi:application --bind 0.0.0.0:9500
      '
    build:
      context: ../backend
      dockerfile: docker/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file: ../backend/.env.fuzz.example
    networks:
      - fuzz-nest-network
    ports:
      - 9500:9500
    healthcheck:
      interval: 10s
      retries: 10
      test: >
        sh -c '
          wget --spider http://backend:9500/a/
        '
      timeout: 10s
      start_period: 5s
  db:
    container_name: fuzz-nest-db
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: ${DJANGO_DB_NAME:-nest_db_fuzz}
      POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD:-nest_user_fuzz_password}
      POSTGRES_USER: ${DJANGO_DB_USER:-nest_user_fuzz}
    healthcheck:
      interval: 5s
      retries: 5
      test: [CMD-SHELL, pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost -p 5432]
      timeout: 5s
    networks:
      - fuzz-nest-network
    volumes:
      - fuzz-db-data:/var/lib/postgresql/data
    ports:
      - 5434:5432
  graphql:
    container_name: fuzz-nest-graphql
    build:
      context: ../backend/docker
      dockerfile: Dockerfile.fuzz
    environment:
      BASE_URL: http://backend:9500
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - fuzz-nest-network

networks:
  fuzz-nest-network:

volumes:
  fuzz-db-data:
