- name: Deploy Nest to Staging
  hosts: nest_staging
  tasks:
    - name: Copy Nginx configuration file
      ansible.builtin.copy:
        src: '{{ github_workspace }}/nginx/staging.conf'
        dest: ~/nginx/nginx.conf
        mode: '0644'

    - name: Copy docker-compose.yml
      ansible.builtin.copy:
        src: '{{ github_workspace }}/docker-compose-staging.yaml'
        dest: ~/docker-compose.yaml
        mode: '0644'

    - name: Ensure backend directory exists
      ansible.builtin.file:
        path: ~/backend
        state: directory
        mode: '0755'

    - name: Copy Backend Makefile
      ansible.builtin.copy:
        src: '{{ github_workspace }}/backend/Makefile'
        dest: ~/backend/Makefile
        mode: '0644'

    - name: Ensure backend directory exists
      ansible.builtin.file:
        path: ~/frontend
        state: directory
        mode: '0755'

    - name: Copy Frontend Makefile
      ansible.builtin.copy:
        src: '{{ github_workspace }}/frontend/Makefile'
        dest: ~/frontend/Makefile
        mode: '0644'

    - name: Copy Makefile
      ansible.builtin.copy:
        src: '{{ github_workspace }}/Makefile'
        dest: ~/Makefile
        mode: '0644'

    - name: Ensure data directory exists
      ansible.builtin.file:
        path: ~/data
        state: directory
        mode: '0755'

    - name: Copy directory recursively
      copy:
        src: '{{ github_workspace }}/data'
        dest: ~/data
        mode: '0755'

    - name: Prune docker images
      shell:
        cmd: docker image prune -f

    - name: Update Docker images
      shell:
        cmd: docker compose pull

    - name: Retart services
      shell:
        cmd: docker compose up -d
