name: Lint Ansible

on:
  pull_request:
    paths:
      - .github/ansible/**
  workflow_dispatch:

permissions: {}

jobs:
  ansible-lint:
    name: Run ansible-lint
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.13'

      - name: Install ansible-lint
        run: pipx install ansible-lint==26.1.1

      - name: Run ansible-lint
        run: make lint-ansible
