name: Update Nest Test Images

on:
  schedule:
    - cron: 30 0 * * *
  workflow_dispatch:

env:
  FORCE_COLOR: 1

permissions:
  contents: read

jobs:
  update-nest-test-images:
    name: Update Nest test images
    if: ${{ github.repository == 'OWASP/Nest' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

      - name: Login to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Update backend test image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          cache-from: |
            type=gha
            type=registry,ref=owasp/nest:test-backend-cache
          cache-to: |
            type=gha,compression=zstd
            type=registry,ref=owasp/nest:test-backend-cache
          context: backend
          file: backend/docker/Dockerfile.test
          platforms: linux/amd64
          push: true
          tags: owasp/nest:test-backend-latest

      - name: Update frontend unit test image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          cache-from: |
            type=gha
            type=registry,ref=owasp/nest:test-frontend-unit-cache
          cache-to: |
            type=gha,compression=zstd
            type=registry,ref=owasp/nest:test-frontend-unit-cache
          context: frontend
          file: frontend/docker/Dockerfile.unit.test
          platforms: linux/amd64
          push: true
          tags: owasp/nest:test-frontend-unit-latest

      - name: Update frontend end-to-end test image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          cache-from: |
            type=gha
            type=registry,ref=owasp/nest:test-frontend-e2e-cache
          cache-to: |
            type=gha,compression=zstd
            type=registry,ref=owasp/nest:test-frontend-e2e-cache
          context: frontend
          file: frontend/docker/Dockerfile.e2e.test
          platforms: linux/amd64
          push: true
          tags: owasp/nest:test-frontend-e2e:latest

      - name: Build and push fuzz-test-backend image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        with:
          cache-from: type=registry,ref=owasp/nest:test-fuzz-backend-cache
          cache-to: type=registry,ref=owasp/nest:test-fuzz-backend-cache,mode=max
          context: backend
          file: backend/docker/Dockerfile.fuzz_tests
          push: true
          tags: owasp/nest:test-fuzz-backend:latest

      - name: Build and push fuzz-test-graphql image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        with:
          cache-from: type=registry,ref=owasp/nest:test-fuzz-graphql-cache
          cache-to: type=registry,ref=owasp/nest:test-fuzz-graphql-cache,mode=max
          context: backend
          file: backend/docker/Dockerfile.graphql_fuzz
          push: true
          tags: owasp/nest:test-fuzz-graphql:latest
