name: Update Nest Test Images

on:
  schedule:
    - cron: 30 0 * * *
  workflow_dispatch:

permissions: {}

env:
  FORCE_COLOR: 1

jobs:
  update-nest-test-images:
    name: Update Nest test images
    if: ${{ github.repository == 'OWASP/Nest' }}
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f

      - name: Login to Docker Hub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Update backend test image
        uses: docker/build-push-action@601a80b39c9405e50806ae38af30926f9d957c47
        with:
          cache-from: |
            type=gha
            type=registry,ref=owasp/nest:test-backend-cache
          cache-to: |
            type=gha,compression=zstd
            type=registry,ref=owasp/nest:test-backend-cache
          context: backend
          file: docker/backend/Dockerfile.test
          platforms: linux/amd64
          push: true
          tags: owasp/nest:test-backend-latest

      - name: Update frontend unit test image
        uses: docker/build-push-action@601a80b39c9405e50806ae38af30926f9d957c47
        with:
          cache-from: |
            type=gha
            type=registry,ref=owasp/nest:test-frontend-unit-cache
          cache-to: |
            type=gha,compression=zstd
            type=registry,ref=owasp/nest:test-frontend-unit-cache
          context: frontend
          file: docker/frontend/Dockerfile.unit.test
          platforms: linux/amd64
          push: true
          tags: owasp/nest:test-frontend-unit-latest

      - name: Update frontend end-to-end test image
        uses: docker/build-push-action@601a80b39c9405e50806ae38af30926f9d957c47
        with:
          cache-from: |
            type=gha
            type=registry,ref=owasp/nest:test-frontend-e2e-cache
          cache-to: |
            type=gha,compression=zstd
            type=registry,ref=owasp/nest:test-frontend-e2e-cache
          context: frontend
          file: docker/frontend/Dockerfile.e2e.test
          platforms: linux/amd64
          push: true
          tags: owasp/nest:test-frontend-e2e-latest

      - name: Build and push fuzz-test-backend image
        uses: docker/build-push-action@601a80b39c9405e50806ae38af30926f9d957c47
        with:
          cache-from: type=registry,ref=owasp/nest:test-fuzz-backend-cache
          cache-to: |
            type=gha,compression=zstd
            type=registry,ref=owasp/nest:test-fuzz-backend-cache
          context: backend
          file: docker/backend/Dockerfile.fuzz
          platforms: linux/amd64
          push: true
          tags: owasp/nest:test-fuzz-backend-latest
    timeout-minutes: 15
